import { useState } from 'react'
import { Link } from 'react-router-dom'
import { usePolling, useResources } from '../api/client'
import { ErrorNotice, Icon, StatusBadge, UrgencyBadge } from '../components/ui'
import { IncidentLog } from '../components/IncidentLog'
import type { Incident } from '../types'

const zones = ['Lawn Stage', 'River Stage', 'Food Village', 'North Gate', 'South Gate', 'Medical Tent']
export default function Safety() {
  const { data, error, loading } = usePolling<Incident[]>('/api/incidents')
  const resources = useResources(); const [zone, setZone] = useState(''); const incidents = data ?? []
  const active = incidents.filter(item => item.status !== 'resolved'); const awaiting = active.filter(item => ['reported', 'awaiting_approval', 'awaiting_clarification'].includes(item.status)); const available = resources.data?.filter(item => item.available).length
  return <div className="page operations-page"><div className="page-heading"><div><div className="eyebrow">RIVERSIDE FESTIVAL · SAFETY LEAD</div><h1>Operations</h1><p>Live incident handling and team coverage.</p></div><Link to="/volunteer" className="button primary"><Icon name="plus" size={18} />Report incident</Link></div><ErrorNotice message={error || resources.error} />
    <div className="stats-grid"><div className="stat-card"><span className="stat-label">Active incidents <Icon name="pulse" /></span><strong>{data ? active.length : '—'}</strong><span>Not resolved</span></div><div className="stat-card"><span className="stat-label">Awaiting review <Icon name="clock" /></span><strong>{data ? awaiting.length : '—'}</strong><span>Require a decision or clarification</span></div><Link to="/safety/resources" className="stat-card"><span className="stat-label">Available responders <Icon name="people" /></span><strong>{available ?? '—'}</strong><span>of {resources.data?.length ?? '—'} on roster</span></Link></div>
    <div className="operations-grid"><section className="site-overview panel"><div className="section-heading"><div><span className="eyebrow">ZONE-LEVEL VIEW</span><h2>Schematic site overview</h2></div>{zone && <button className="clear-button" onClick={() => setZone('')}>Clear selection</button>}</div><p className="map-note">Zone labels support coordination only; they are not GPS or live location tracking.</p><div className="site-map">{zones.map((name, index) => { const count = active.filter(item => item.location === name).length; return <button key={name} className={`site-zone z${index} ${zone === name ? 'selected' : ''}`} onClick={() => setZone(zone === name ? '' : name)}><span>{name}</span><b>{count || '—'}</b></button> })}</div></section><section className="incident-queue panel"><div className="section-heading"><div><span className="eyebrow">PRIORITY ORDER</span><h2>Incident queue</h2></div><span className="live-label"><span className="dot" />5s polling</span></div>{loading ? <p className="loading-state">Loading incident queue…</p> : active.length ? <div className="queue-list">{active.slice(0, 5).map(item => <Link key={item.id} to={`/safety/incidents/${item.id}`} className="queue-item"><div><UrgencyBadge urgency={item.urgency} /><strong>{item.summary}</strong><span><Icon name="pin" size={14} />{item.location || 'Unconfirmed location'}</span></div><StatusBadge status={item.status} /></Link>)}</div> : <p className="loading-state">No active incidents.</p>}</section></div>
    <IncidentLog incidents={incidents} zone={zone} /></div>
}
