import { test, expect } from '@playwright/test'

test('volunteer report, clarification, safety approval, and resolution persist', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/volunteer')
  await page.getByRole('button', { name: 'Medical incident', exact: true }).click()
  await page.getByRole('button', { name: 'Submit Incident', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Person collapsed and appears dizzy' })).toBeVisible()
  await page.getByLabel('Is the person breathing normally?').fill('Yes, they are breathing normally.')
  await page.getByRole('button', { name: 'Send update', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Update sent')
  await page.getByRole('link', { name: 'View incident', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Suggested response', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Approve response', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Approved response', exact: true })).toBeVisible()
  await expect(page.getByText('Response dispatched', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Approved response', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Resolve incident', exact: true }).click()
  await page.getByLabel('Resolution note', { exact: true }).fill('First aid team completed the response. Incident closed.')
  await page.getByRole('button', { name: 'Confirm resolution', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Draft incident report', exact: true })).toBeVisible()
  await expect(page.getByText('Resolved', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Back to overview', exact: true }).click()
  await page.getByRole('button', { name: 'Resolved', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Person collapsed and appears dizzy' })).toBeVisible()
  expect(errors).toEqual([])
})

test('lead can reject then modify a response', async ({ page }, testInfo) => {
  await page.goto('/volunteer')
  await page.getByRole('button', { name: 'Lost child', exact: true }).click()
  await page.getByRole('button', { name: 'Submit Incident', exact: true }).click()
  await page.getByRole('link', { name: 'View incident', exact: true }).click()
  await page.getByRole('button', { name: 'Reject', exact: true }).click()
  await page.getByLabel('Reason for this decision', { exact: true }).fill('Use the welfare volunteer at the gate.')
  await page.getByRole('button', { name: 'Confirm rejection', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Suggestion rejected')
  await page.getByRole('button', { name: 'Modify', exact: true }).click()
  await page.getByLabel('Reason for this decision', { exact: true }).fill('Confirmed the response with the team.')
  await page.getByLabel('Response actions (one per line)', { exact: true }).fill('Attend North Gate and contact the reporting volunteer.')
  await page.getByRole('button', { name: 'Approve modified response', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Approved response', exact: true })).toBeVisible()
  await expect(page.getByText('Attend North Gate and contact the reporting volunteer.', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('incident-desktop.png'), fullPage: true })
  await page.goto('/safety')
  await expect(page.getByRole('heading', { name: 'Incident board' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('overview-desktop.png'), fullPage: true })
})

test('mobile screens fit the viewport and reporting remains usable', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  for (const route of ['/volunteer', '/safety', '/safety/resources']) {
    await page.goto(route)
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
    const sizes = await page.evaluate(() => ({ viewport: window.innerWidth, content: document.documentElement.scrollWidth }))
    expect(sizes.content).toBeLessThanOrEqual(sizes.viewport)
  }
  await page.goto('/volunteer')
  await page.getByLabel('What’s happening?', { exact: true }).fill('There is a blocked access path at Food Village.')
  await page.screenshot({ path: testInfo.outputPath('volunteer-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: 'Submit Incident', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Your report is with the safety lead')
  await page.getByRole('link', { name: 'View incident', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Approve response' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})
